fix: worklow build, failing job deploy

diff --git a/.github/actions/publish-container-image/action.yaml b/.github/actions/publish-container-image/action.yaml
--- a/.github/actions/publish-container-image/action.yaml
+++ b/.github/actions/publish-container-image/action.yaml
@@ -29,12 +29,22 @@ runs:
     using: composite
 
     steps:
+        - name: Install buildah if not exists
+          shell: bash
+          run: |
+            if ! command -v buildah &> /dev/null
+            then
+                echo "Buildah not found, installing..."
+                sudo apt-get update
+                sudo apt-get -y install buildah
+            fi
+
         - name: Build image
           id: build-image
           uses: redhat-actions/buildah-build@v2
           with:
-              image: "${{ inputs.namespace != '' && inputs.namespace || inputs.username }}/${{ inputs.image_name }}"
-              tags: "${{ inputs.image_tag }}"
+              image: ${{ inputs.namespace != '' && inputs.namespace || inputs.username }}/${{ inputs.image_name }}
+              tags: ${{ inputs.image_tags }}
               context: ${{ inputs.context }}
               containerfiles: ${{ inputs.containerfile }}
 
